# Generated by Django 5.1.3 on 2024-11-25 05:09

import Invoices.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=33, primary_key=True, serialize=False, verbose_name='id')),
                ('PostalCode', models.CharField(max_length=20, verbose_name='postal_code')),
                ('Address', models.TextField(verbose_name='address')),
                ('Province', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=255, verbose_name='province')),
                ('Status', models.CharField(choices=[('صادر شده', 'صادر شده'), ('رد شده', 'رد شده')], max_length=255, verbose_name='status')),
                ('Township', models.CharField(max_length=255, verbose_name='township')),
                ('Issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issueDate')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.CharField(default=Invoices.models.randomUID, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('organization_1', models.CharField(max_length=255, verbose_name='organization_1')),
            ],
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(default=Invoices.models.randomUID, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='uid')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='code')),
                ('phone', models.CharField(max_length=11, validators=[Invoices.models.User.phoneValidator], verbose_name='phone')),
                ('gender', models.BooleanField(default=False, verbose_name='gender')),
                ('father_name', models.CharField(max_length=255, verbose_name='father_name')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('result', models.CharField(choices=[('تایید شده', 'تایید شده'), ('رد شده', 'رد شده')], max_length=255, verbose_name='result')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiries_lists', to='Invoices.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='License',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Licences', to='Invoices.license', verbose_name='licesne'),
        ),
        migrations.AddField(
            model_name='data',
            name='Issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Invoices.user'),
        ),
    ]
